import kvstore.keys as keys

REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_DB_NUM = 0
REDIS_HEALTH_CHECK_INT = 30
REDIS_SUB_SLEEP_TIME = 0.001
SQLITE_FILENAME = 'kvstore.db'

PERSISTENT_KEYS = [
    keys.NODE_ID,
    keys.ACCESS_KEY,
    keys.NODE_CONFIG,
    keys.WIFI_AP_AVAILABLE,
    keys.WIFI_AP_CONFIG,
]
