[tool.black]
line-length = 120
target-version = ['py310']
include = 'src/.*\.pyi?$'

[tool.flake8]
max-line-length = 120
extend-ignore = "E203"
include = 'src/.*\.pyi?$'

[tool.isort]
honor_noqa = true
include_trailing_comma = true
line_length = 120
multi_line_output = 3
skip_gitignore = true
star_first = true
src_paths = ["src"] 
