[package]
name = "ammp-edge"
version = "0.1.1"
authors = ["AMMP Technologies B.V. <dev@ammp.io>"]
edition = "2021"
description = "Edge application for AMMP"
repository = "https://github.com/ammpio/ammp-edge"

[dependencies]
anyhow = "1.0.66"
backoff = "0.4.0"
chrono = "0.4.23"
dotenv = "0.15.0"
env_logger = { version = "0.9.3", default-features = false }
flume = "0.10"
getrandom = "0.2.8"
hex = "0.4.3"
kvstore = { path = "kvstore" }
log = "0.4.17"
native-tls = "0.2.11"
nix = { version = "0.25.0", features = ["socket"] }
once_cell = "1.16.0"
pico-args = "0.5.0"
rumqttc = { version = "0.17.0", default-features = false }
rusqlite = { version = "0.28.0", features = ["serde_json"] }
serde = {version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
sysinfo = { version = "0.26.7", default-features = false }
thiserror = "1.0.37"
ureq = { version = "2.5.0", default-features = false, features = ["json", "native-tls"] }

[dev-dependencies]
assert_cmd = "2.0.6"
mockito = "0.31.0"
regex = "1.7.0"
predicates = "2.1.3"
temp-env = "0.3.1"
tempfile = "3.3.0"

[[bin]]
name = "ae"
path = "src/main.rs"

[workspace]
members = [
    "kvstore"
]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
opt-level = "z"  # Optimize for size.
codegen-units = 1
