name: stromm
version: '0.2.3'
summary: Secure Telemetry, Remote Operation and Monitoring for Mini-Grids
description: |
    Manages data collection and forwarding for AMMP.

grade: devel
confinement: strict

apps:
  stromm:
    command: bin/stromm -d
#    daemon: simple
    plugs:
      - network

parts:
  stromm:
    plugin: python
    python-version: python3
    source: git@gitlab.com:ammp-services/stromm.git
    stage-packages:
        - libsnmp-dev
        - snmp-mibs-downloader
        - libsystemd-dev
        - python3-systemd
        - python3-netifaces
# Just to get the remote cfg YAML file
  stromm-remote-cfg:
    plugin: dump
    source: git@gitlab.com:ammp-services/stromm.git
    prime:
      - remote.yml
# The following builds a blank "drivers" directory that's mapped to the drivers snap
  drivers:
    plugin: nil
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/drivers
    stage:
      - drivers

plugs:
  drivers:
    interface: content
    content: drivers
    target: $SNAP/drivers
    default-provider: stromm-drivers:drivers